server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: credit
  datasource:
    url: jdbc:h2:mem:loandb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

app:
  security:
    admin:
      username: admin
      password: admin123